function validate_allm_campaign(campaign, config, info, requireComplete)

if nargin < 4
    requireComplete = true;
end
assert(strcmp(campaign.campaignId, config.campaignId), 'allm:CampaignMismatch', ...
    'Campaign ID differs.');
assert(strcmp(campaign.protocolVersion, config.protocolVersion) && ...
    strcmp(campaign.implementationVersion, config.implementationVersion), ...
    'allm:CampaignMismatch', 'Campaign version differs.');
assert(strcmp(campaign.configFingerprint, info.fingerprint), 'allm:CampaignMismatch', ...
    'Scientific configuration differs.');
assert(isequal(campaign.seedList, info.seedList), 'allm:CampaignMismatch', ...
    'Campaign seed list differs.');
assert(isequal(campaign.config.methods, config.methods), 'allm:CampaignMismatch', ...
    'Configured method order differs.');
assert(numel(campaign.results) == config.numReplicates, 'allm:CampaignMismatch', ...
    'Campaign result count differs.');
if isfield(campaign, 'completedMask')
    assert(isequal(size(campaign.completedMask), [1, config.numReplicates]), ...
        'allm:CampaignMismatch', 'Completion mask shape differs.');
    if requireComplete
        assert(all(campaign.completedMask), 'allm:CampaignIncomplete', ...
            'Campaign completion mask contains missing replicates.');
    end
end
for r = 1:config.numReplicates
    if isempty(campaign.results{r})
        assert(~requireComplete, 'allm:CampaignIncomplete', ...
            'Replicate
        continue;
    end
    validate_replicate(campaign.results{r}, config, r, info.seedList(r));
end
if requireComplete
    assert(isfield(campaign, 'summary'), 'allm:CampaignMismatch', ...
        'Complete campaign has no summary.');
    validate_summary(campaign.summary, config);
end
end

function validate_replicate(replicate, config, index, environmentSeed)
assert(isstruct(replicate) && replicate.replicateIndex == index && ...
    replicate.envSeed == environmentSeed, 'allm:CampaignMismatch', ...
    'Replicate
assert(isfield(replicate, 'seedPlan') && ...
    replicate.seedPlan.environment == environmentSeed, 'allm:CampaignMismatch', ...
    'Replicate
assert(isfield(replicate, 'env') && replicate.env.metadata.seed == environmentSeed, ...
    'allm:CampaignMismatch', 'Replicate %d environment provenance is invalid.', index);
for m = 1:numel(config.methods)
    key = config.methods{m};
    assert(isfield(replicate, key), 'allm:CampaignMismatch', ...
        'Replicate
    result = replicate.(key);
    assert(isfield(replicate.seedPlan, key) && ...
        result.seed == replicate.seedPlan.(key).policy && ...
        result.feedbackSeed == replicate.seedPlan.(key).feedback, ...
        'allm:CampaignMismatch', 'Replicate %d method seeds are invalid.', index);
    assert(numel(result.selectedArm) == config.T && ...
        all(result.selectedArm >= 1 & result.selectedArm <= config.K), ...
        'allm:CampaignMismatch', 'Replicate %d selections are invalid.', index);
    expectedLength = 1 + floor(config.T / config.recordEvery);
    assert(numel(result.Regret) == expectedLength && numel(result.Delay) == expectedLength && ...
        all(isfinite(result.Regret)) && all(isfinite(result.Delay)) && ...
        isfinite(result.finalRegret) && isfinite(result.finalDelay) && ...
        isfinite(result.runtimeSeconds), 'allm:CampaignMismatch', ...
        'Replicate
end
end

function validate_summary(summary, config)
assert(summary.numReplicates == config.numReplicates, 'allm:CampaignMismatch', ...
    'Summary replicate count differs.');
steps = 0:config.recordEvery:config.T;
assert(isequal(summary.recordSteps, steps), 'allm:CampaignMismatch', ...
    'Summary record grid differs.');
for m = 1:numel(config.methods)
    key = config.methods{m};
    source = summary.(key);
    scalarFields = {'finalRegret', 'finalDelay', 'runtimeSeconds', 'switchCount'};
    for f = 1:numel(scalarFields)
        values = source.(scalarFields{f});
        assert(isfinite(values.mean) && isfinite(values.std) && isfinite(values.se) && ...
            numel(values.ci95) == 2, 'allm:CampaignMismatch', ...
            'Summary scalar metric is invalid.');
    end
    curveFields = {'regretCurve', 'delayCurve'};
    for f = 1:numel(curveFields)
        values = source.(curveFields{f});
        assert(numel(values.mean) == numel(steps) && numel(values.std) == numel(steps) && ...
            isequal(size(values.ci95), [2, numel(steps)]) && all(isfinite(values.mean)), ...
            'allm:CampaignMismatch', 'Summary curve metric is invalid.');
    end
end
end